import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/libs/utils/utils";
import { Toaster } from "sonner";
import Header from "@/components/layout/header";
import { TooltipProvider } from "@/components/ui/tooltip";

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn(
        "h-full",
        "antialiased",
        geistSans.variable,
        geistMono.variable,
        "font-sans",
        inter.variable,
      )}
    >
      <body className="h-screen overflow-hidden bg-white-primary">
        <TooltipProvider>
          <div className="flex h-full flex-col">

            <header className="sticky top-0 z-50 shrink-0 bg-white-primary">
              <Header />
            </header>


            <main className="flex-1 flex flex-col overflow-y-auto h-full">

              {children}

            </main>
          </div>
        </TooltipProvider>

        <Toaster />
      </body>
    </html>
  );
}
